// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Prisma 7's config schema has no `directUrl` field (only `url` and
    // `shadowDatabaseUrl` - confirmed against @prisma/config's own types).
    // Migrations run through this same pooled DATABASE_URL; DIRECT_URL is
    // unused by Prisma itself, kept in .env only in case a future need
    // (e.g. a script that wants an unpooled connection) comes up.
    url: env("DATABASE_URL"),
  },
});
